all: generated/bashrc generated/bash_profile

install:
	cp -i $(PWD)/generated/bashrc $(HOME)/.bashrc
	cp -i $(PWD)/generated/bash_profile $(HOME)/.bash_profile

diff:
	diff $(PWD)/generated/bashrc $(HOME)/.bashrc || true
	diff $(PWD)/generated/bash_profile $(HOME)/.bash_profile || true

generated/%:
	mkdir -p generated
	{ echo "### Generated by $(PWD)/Makefile";                 \
		for f in $(@F).d/*.bash ;                              \
		do                                                     \
			echo "source $(PWD)/$$f";                          \
		done ;                                                 \
	}  > $@

clean:
	rm -rf generated/
